class Codes:

    HEALTH_OK = "HEALTH_OK"
    LIVE_OK = "LIVE_OK"
    HEALTH_ERROR = "HEALTH_ERROR"

    PUNISHMENT_CREATED_OK = "PUNISHMENT_CREATED_OK"
    PUNISHMENT_CHECK_OK = "PUNISHMENT_CHECK_OK"
    PUNISHMENT_HISTORY_OK = "PUNISHMENT_HISTORY_OK"
    PUNISHMENT_REVOKED_OK = "PUNISHMENT_REVOKED_OK"
    PUNISHMENT_NOT_FOUND = "PUNISHMENT_NOT_FOUND"
    PUNISHMENT_ALREADY_REVOKED = "PUNISHMENT_ALREADY_REVOKED"